---
# Requires the RabbitMQ Cluster Kubernetes Operator.
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: app-rabbitmq
  namespace: messaging
  labels:
    app.kubernetes.io/name: app-rabbitmq
    app.kubernetes.io/component: message-broker
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  persistence:
    storageClassName: REPLACE_ME
    storage: 20Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - app-rabbitmq
          topologyKey: kubernetes.io/hostname
